apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "opsgenie_acknowledge_alert"
  description: "Acknowledge an OpsGenie alert."
  vendor: opsgenie
  type: notification

envs:
  - name: USE_EU_API
    description: "set to true to use 'api.eu.opsgenie.com' instead of default 'api.opsgenie.com'"
    type: "string"
    required: false
  - name: ALERT_ID
    description: "The id of the alert to acknowledge."
    type: string
    required: true
    example: "18804a84-4708-4447-b343-f7fd18e8ff44"

integrations:
  - opsgenie