apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "redis_hset"
  description: "Perform Redis hset call (https://redis.io/commands/hset)"
  vendor: redis
  type: remediation

envs:
  - name: REDIS_IP 
    description: "Destination redis IP address (required)"
    type: "string"
    required: true
    example: "127.0.0.1"
  - name: REDIS_PASSWORD
    description: "Destination redis password (optional)"
    type: "string"
    example: '{{ secret "REDIS_PASSWORD" }}'
  - name: REDIS_URL 
    description: "Redis url (required if there is no redis IP address specified)"
    type: "string"
    example: "redis://<username>:<password>@<host>:<port>/<database>"
  - name: KEY 
    description: "Item key"
    type: "string"
    required: true
    example: "mykey"
  - name: FIELD 
    description: "Item field"
    type: "string"
    required: true
    example: "myfield"

outputs:
  - name: output 
    description: "The number of fields that were added."
    type: string
    example: "1"
