apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "kubectl_version"
  description: "Print kubectl client and server version"
  vendor: kubernetes
  type: hydration

envs:
  - name: KUBECONFIG_CONTENT
    description: "kubeconfig content for authentication. base64 encoded kubeconfig file. could be provided by kubernetes integration as well."
    type: "string"
    required: false
    example: '{{ secret "KUBECONFIG_CONTENT" }}'
  - name: FORMAT
    description: "Output format. default to 'json' for other formats see https://kubernetes.io/docs/reference/kubectl/overview/#output-options"
    type: "string"
    example: "wide"
  - name: SHORT
    description: "Print short version description. (Default is true)"
    type: "bool"
    required: false
    example: "false"
  - name: CLIENT_ONLY
    description: "Client version only (no server required). (Default is false)"
    type: "bool"
    required: false
    example: "true"
integrations:
  - k8s

outputs:
  - name: clientVersion
    description: "Kubectl client version"
    type: "json"
    example: '{"buildDate":"2020-07-15T16:58:53Z","compiler":"gc","gitCommit":"dff82dc0de47299ab66c83c626e08b245ab19037","gitTreeState":"clean","gitVersion":"v1.18.6","goVersion":"go1.13.9","major":"1","minor":"18","platform":"linux/amd64"}'
  - name: serverVersion
    description: "Kubernetes server version"
    type: "json"
    example: '{"buildDate":"2020-10-28T09:23:22Z","compiler":"gc","gitCommit":"7ed5ddc0e67cb68296994f0b754cec45450d6a64","gitTreeState":"clean","gitVersion":"v1.16.15.4300","goVersion":"go1.13.15b4","major":"1","minor":"16+","platform":"linux/amd64"}'