apiVersion: stackpulse.io/v1
kind: Step
metadata:
  imageName: "us-docker.pkg.dev/stackpulse/public/jenkins/get-build"
  version: 1.0.0
  name: "jenkins_get_build"
  description: "Return build details"
  vendor: jenkins
  type: remediation

envs:
  - name: USERNAME
    description: "Username for login."
    required: true
    type: "string"
  - name: PASSWORD
    required: true
    description: "Password for login."
    type: "string"
  - name: HOST
    description: "Jenkins host."
    required: true
    type: "string"
    example: "http://org.jenkins.com:8080/"
  - name: JOB_NAME
    description: "Job name to get build of."
    required: true
    type: "string"
  - name: BUILD_ID
    description: "The id of the build to get."
    required: true
    type: "int"

outputs:
  - name: result
    description: "The result of the build."
    type: "string"
    example: "SUCCESS"
  - name: duration
    description: "The duration of the build."
    type: "int"
    example: 11492
  - name: name
    description: "The display name of the build."
    type: "string"
    example: "#19"
  - name: timestamp
    description: "The time the build was created in datetime format"
    type: "string"
    example: "2021-02-21T23:34:22Z"
  - name: api_object
    description: "The entire build_response object from the Jenkins api"
    type: "json"
    example: |
      {"api_object":{"Actions":[{"parameters":[{"Name":"DECK_ID","Value":"9ccae8sl8s2c"}],"causes":null,"buildsByBranchName":null,"lastBuiltRevision":{"SHA1":"","branch":null},"remoteUrls":null,"scmName":"","mercurialNodeName":"","mercurialRevisionNumber":"","subdir":null,"TotalCount":0,"UrlName":""},{"parameters":null,"causes":[{"_class":"hudson.model.Cause$UserIdCause","shortDescription":"Started by user admin","userId":"admin","userName":"admin"}],"buildsByBranchName":null,"lastBuiltRevision":{"SHA1":"","branch":null},"remoteUrls":null,"scmName":"","mercurialNodeName":"","mercurialRevisionNumber":"","subdir":null,"TotalCount":0,"UrlName":""}],"artifacts":[],"building":false,"builtOn":"","changeSet":{"items":[],"kind":"","revision":null},"changeSets":null,"culprits":[],"description":null,"duration":11492,"estimatedDuration":11306,"executor":null,"displayName":"#19","fullDisplayName":"Draw a Card #19","id":"19","keepLog":false,"number":19,"queueId":92,"result":"SUCCESS","timestamp":1613950462939,"url":"http://localhost:8080/job/Draw%20a%20Card/19/","mavenArtifacts":null,"mavenVersionUsed":"","FingerPrint":null,"runs":null}}