apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "curl_request"
  description: "Make an HTTP(S) request with cURL"
  vendor: curl
  type: remediation

envs:
  - name: FORMAT
    description: 'cURL response format. Can be json \\ raw (the output will be added to the context as is under "output" key) \\ print (will just print the output without any addition to the context)'
    type: "string"
    default: "json"
    required: true

args:
  - name: url
    description: "URL to make a request to"
    type: "string"
    required: true
    default: "https://api-server/v1/some_api_endpoint"
