apiVersion: stackpulse.io/v1
kind: Step
metadata:
  imageName: "us-docker.pkg.dev/stackpulse/public/ssh/ssh-command-gcloud-secret"
  version: 1.0.0
  name: "ssh_command_with_gcloud_secret"
  description: "Connect to remote SSH server, authenticating with a content of Google Cloud Secret, and execute command(s)"
  vendor: gcp
  type: remediation 

envs:
  - name: SSH_KEY_SECRET_NAME
    description: "The name of the secret in the Google Cloud Secret Manager containing the SSH Certificate to be used for connection"
    type: "string"
  - name: SSH_CLIENT
    description: "Address of the server to connect to, i.e. user@destination:port"
    type: "string"    
  - name: SSH_COMMAND
    description: "One (or multiple, separated with a semicolon) command(s) to execute"
    type: "string"    
  - name: INTEGRATION_TYPE_GCLOUD
    description: "A Google Cloud integration having a role to access Google Cloud Secrets Manager (alternatively - AUTH_CODE for Base64-encoded GCP Service Account Token)"
    type: secret
    required: true
    