apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "kafka_alter_topic"
  description: "Alter a Kafka topic configuration"
  vendor: kafka
  type: remediation

envs:
  - name: ZOOKEPER_HOST
    required: true
    description: "Zookeeper host"
    type: string
    example: "<host>:<port>"
  - name: TOPIC_NAME
    required: true
    type: string
    description: "Topic name to alter"
    example: "my-topic"
  - name: CONFIG_NAME
    required: true
    type: string
    description: "Config name"
    example: "advertised.listeners"
  - name: CONFIG_VAL
    required: true
    type: string
    description: "Config value"
    example: "PLAINTEXT"

outputs:
  - name: basic-logs
    description: "Raw output for the command"
    type: "string"
