apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "istio_proxy_status"
  description: "Run a proxy-status command on your Istio cluster."
  vendor: istio
  type: triage

envs:
  - name: KUBECONFIG_CONTENT
    description: "Kubernetes configuration file content."
    type: "string"
    required: false
  - name: USE_LOCAL_TOKEN
    description: "True by default, use local token to authenticate to kubernetes (if running inside Pod on same cluster).Must specify this or KUBECONFIG_CONTENT."
    type: "bool"
    required: false
  - name: ISTIO_NAMESPACE
    description: "Istio system namespace (default\: istio-system)"
    type: "string"
    required: false
  - name: CONTEXT
    description: "The name of the kubeconfig context to use."
    type: "string"
    required: false
  - name: NAMESPACE
    description: "Config namespace."
    type: "string"
    required: false
  - name: POD
    description: "Specific Pod to query\: [<pod-name[.namespace]>]."
    type: "string"
    required: false

integrations:
  - k8s