apiVersion: stackpulse.io/v1
kind: Step
metadata:
  imageName: "us-docker.pkg.dev/stackpulse/public/envoy/listeners"
  version: 1.0.0
  name: "envoy_listeners"
  description: "Get listeners from Envoy's administrative interface."
  vendor: envoy
  type: triage

envs:
  - name: HOST
    description: "Evnoy administrative interface host (ip/dns)."
    type: "string"
    required: true
  - name: PORT
    description: "Evnoy administrative interface port (8001 by default)."
    type: "string"
    required: false
  - name: SSL
    description: "Whatever to use ssl when connecting to the Envoy's administrative interface."
    type: "bool"
    required: false
  - name: UNSAFE_SSL
    description: "Whatever to honor invalid ssl certificates when connecting to Envoy's administrative interface."
    type: "bool"
    required: false