apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "atlassian_jira_delete_issue"
  description: "Delete existing Jira issue"
  vendor: jira
  type: notification

envs:
  - name: JIRA_SITE_NAME
    description: "The Jira Cloud site name, the prefix before \".atlassian.net\", usually your organization name."
    type: "string"
    required: true
    example: "<organization>"
  - name: ISSUE_ID
    description: "ID of the Jira issue to be deleted."
    type: "string"
    required: true
    example: "ID-1234"

outputs:
  - name: success
    description: "If the issue was deleted successfully this key will be true."
    type: "bool"
    example: "true"

integrations:
  - jira
