apiVersion: stackpulse.io/v1
kind: Step
metadata:
  imageName: "us-docker.pkg.dev/stackpulse/public/rundeck/execution/abort"
  version: 1.0.0
  name: "rundeck_abort_execution"
  description: "Abort a running execution."
  vendor: rundeck
  type: remediation

envs:
  - name: HOST
    description: "Rundeck host name or IP."
    type: "string"
    required: true
    example: "rundeck.server"
  - name: PORT
    description: "Rundeck port."
    type: "string"
    required: true
    example: "4040"
  - name: AUTH_TOKEN
    description: "Token for authentication."
    type: "string"
    required: true
    example: "DRUVEuCdENoPkUpDkcDcdd6PeKkPdurc"
  - name: EXECUTION_ID
    description: "ID of running execution to abort."
    type: "int"
    required: true
    example: 93
  - name: HTTP_SCHEME
    description: "HTTP Request scheme. can be either 'http' or 'https'."
    type: "string"
    default: "https"
    example: "http"


outputs:
  - name: abortion_status
    description: "Whether the execution was aborted. will be one of - 'pending', 'failed', or 'aborted'."
    type: "string"
    example: "failed"
  - name: reason
    description: "The reason for the failure, only if the abortion failed."
    type: "string"
    example: "Job is not running"
  - name: execution_status
    description: "Status of the execution after abortion attempt."
    type: "string"
    example: "succeeded"
  - name: execution_id
    description: "ID of the execution."
    type: "int"
    example: 93
  - name: api_object
    description: "Information about the Execuyion Abortion Attempt."
    type: "json"
    example: '{"abort"\:{"status"\:"failed","reason"\:"Job is not running"},"execution"\:{"id"\:"93","status"\:"succeeded","href"\:"http\://192.168.50.2\:4440/api/38/execution/93","permalink"\:"http\://rundeck.server\:4440/project/anvils/execution/show/93"}}'