apiVersion: stackpulse.io/v1
kind: Step
metadata:
  imageName: "us-docker.pkg.dev/stackpulse/public/opsgenie/incident/create"
  version: 1.0.0
  name: "opsgenie_create_incident"
  description: "Create a new OpsGenie incident for a service"
  vendor: opsgenie
  type: notification

envs:
  - name: USE_EU_API
    description: "set to true to use 'api.eu.opsgenie.com' instead of default 'api.opsgenie.com'"
    type: "string"
    required: false
  - name: SERVICE_NAME
    description: "Name of the OpsGenie service to create incident for."
    type: "string"
    required: true
    example: "SP-Service"
  - name: MESSAGE
    description: "Incident message, will be displayed as the incident title in OpsGenie."
    type: "string"
    required: true
    example: "Incident Title"
  - name: DESCRIPTION
    description: "Incident Description, will be displayed as the incident description in OpsGenie."
    type: "string"
    required: true
    example: "Incident Description"
  - name: PRIORITY
    description: "Incident priority,  should be one of 'P1', 'P2', 'P3', 'P4' and 'P5' or empty. (default is 'P3')."
    type: "string"
    required: false
    example: "P1"

integrations:
  - opsgenie